### ISSUE TITLE
Intermediate Speedtest results fail to write to terminal

### ISSUE THREAD

**Issue by MCOfficer** [KoalaBear84/OpenDirectoryDownloader#43] opened 2020-11-04 09:03 UTC
**Describe the bug**
There is a deadlock happening whenever ODD is trying to write the intermediate speedtest results to the terminal. As soon as i hit enter, the deadlock is resolved. If the speedtest has been running for a while, an error is produced and the speedtest shows up as failed in the final results, otherwise it resumes as normal.

```
Starting speedtest (10-25 seconds)...
Test file: 896 MiB http://works.with/any.url
Downloaded: 4.49 MiB, Time: 295s, Speed: 4.5 MB/s (36 mbit)2020-11-04 08:42:33.1965 [15] ERROR OpenDirectoryIndexer.StartIndexingAsync Speedtest failed System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Max[TSource](IEnumerable`1 source, Func`2 selector)
   at OpenDirectoryDownloader.Library.SpeedtestFromStream(Stream stream, Int32 seconds) in D:\a\OpenDirectoryDownloader\OpenDirectoryDownloader\OpenDirectoryDownloader\Library.cs:line 205
   at OpenDirectoryDownloader.Library.DoSpeedTestHttpAsync(HttpClient httpClient, String url, Int32 seconds) in D:\a\OpenDirectoryDownloader\OpenDirectoryDownloader\OpenDirectoryDownloader\Library.cs:line 140
   at OpenDirectoryDownloader.OpenDirectoryIndexer.<>c__DisplayClass51_0.<<StartIndexingAsync>b__0>d.MoveNext() in D:\a\OpenDirectoryDownloader\OpenDirectoryDownloader\OpenDirectoryDownloader\OpenDirectoryIndexer.cs:line 367
Http status codes
```

**To Reproduce**
1. Open any shell on linux (Test with zsh and bash, over SSH and in a terminal emulator)
2. Run a scan with the `-s` flag
3. Wait for the "Starting speedtest" output. No further output (Apart from "Test file: ...") should appear).
4. Wait for a solid minute or two, then hit enter
5. The intermediate output will appear, along with the error right behind it (see paste above).

[Video of a reproduction](https://asciinema.org/a/NHeWMPyXGSMhGv3jjfIB4L1tW) (Skip to 1:25 if you don't want to wait)

**Expected behavior**
The intermediate results should be written to the terminal. If that turns out to be impossible, it should print a warning and proceed with the speedtest.

**Machine 1:**
 - OS: Ubuntu 18.04.5 LTS
 - Version: v1.7.0.3
 - Shell: zsh over ssh

**Machine 2:**
 - OS: Manjaro Linux 20.1.2 "Mikah"
 - Version: v1.7.0.3
 - Shell: bash and zsh in yakuake

**Comment by KoalaBear84** [comment] 2020-11-04 09:25
Hmm, that is some strange behavior. Maybe Linux/unix doesn't support this way of console/terminal refreshing on the way it currently is implemented.

![image](https://user-images.githubusercontent.com/5886900/98093124-ce919e00-1e87-11eb-87a1-00cfe23612fa.png)

Maybe in the meantime only do that on Windows until it is solved. Will create an update for that when I have time.

**Comment by MCOfficer** [comment] 2020-11-04 09:54
I gave the code a quick look-over, and it seems sound to me. It may not work as expected, but it definitely shouldn't deadlock.

This seems eerily similar to https://stackoverflow.com/questions/15143931/strange-behaviour-of-console-readkey-with-multithreading. With that in mind, I tested with .NET runtime 3.1.9 and 3.1.8. I'll try to compile and run it with v5.0.100-rc.2.

**Comment by MCOfficer** [comment] 2020-11-04 10:03
Can confirm that this also happens on v5.0.100-rc.2. I won't test with 4.x because i can't seem to find any packages for linux.

**Comment by KoalaBear84** [comment] 2020-11-04 10:08
Thanks for checking, currently using 5 RC2 myself too and will probably switch to it soon.

Correct, there is no 4.x :)

That is because of the legacy .NET Framework which is Windows only and was also at 4.x. And the separate .NET Core which is the crossplatform version of it which is currently at .NET Core 3.1.9. They are skipping .NET Core 4.x and are going directly to 5.x and jump over the .NET Framework 4.x version range because of the possible confusion.

On November 10 the final of .NET 5.0 will be released, and yes, from that moment on the "Core" will be left out of the name because it is the only version of .NET from now on. And every year in November there will be a new major release.

**Comment by MCOfficer** [comment] 2020-11-04 10:09
Just to make sure: you did catch my edit, right?

**Comment by KoalaBear84** [comment] 2020-11-04 10:13
Ahh, I saw, but didn't thought about it after my comment. OK. You indeed need the runtime for it. But I see it is still trying to start with 3.1.0.

**Comment by MCOfficer** [comment] 2020-11-04 10:14
> Ahh, I saw, but didn't thought about it after my comment. OK. You indeed need the runtime for it. But I see it is still trying to start with 3.1.0.

I have the 5.0 runtime installed, but yes, it seems to require 3.1. Which kinda sucks - by my understanding, a potential .NET bug as described on SO would be part of the runtime.

**Comment by KoalaBear84** [comment] 2020-11-04 10:17
You could try it by changing this in the 4 .csproj files (maybe only in OpenDirectoryDownloader.csproj would already work).

`<TargetFramework>netcoreapp3.1</TargetFramework>` -> `<TargetFramework>net5.0</TargetFramework>`

**Comment by MCOfficer** [comment] 2020-11-04 10:32
That worked, I've reproduced it on 5.0.

**Comment by KoalaBear84** [comment] 2020-11-04 10:55
OK, thanks.

Steps:
1. Only do this on Windows.
2. Make a small project to reproduce and try to find a fix for it

**Comment by MCOfficer** [comment] 2020-11-04 11:25
Here's something that might help: When i press enter in time (while the speedtest still runs), it resolves the deadlock immediately and the download information keeps updating afterwards: https://asciinema.org/a/rFiDtkSle7EwiP0h8kesnLq8f

Judging by the error, the deadlock has to happen while the stream is already open, so it has to be while or just before printing output on the very first iteration. Perhaps this can be worked around with by printing something *before* the first iteration, then erasing it with the initial `ClearCurrentLine()`?

**Comment by KoalaBear84** [comment] 2020-11-04 11:27
Thanks for the update. Hopefully 😇

**Closed** 2020-11-04 12:45 UTC

**Comment by KoalaBear84** [comment] 2020-11-04 12:49
Released https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v1.7.0.4
