### ISSUE TITLE
Error The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by a8underscore** [KoalaBear84/OpenDirectoryDownloader#61] opened 2021-01-09 23:32 UTC
Hey, im trying to find the size of a mega folder useing this tool (i know this isnt really the correct use but i tought i could give it a try) , the exact command im running is `./OpenDirectoryDownloader -u "http://mega.nz/folder/30MlkQib#RDOaGzmtFEHkxSYBaJSzVA" -e
`
but the output im getting is
https://paste.gg/p/anonymous/89418b73b9734f00b2965b2d4f35c153
and it keeps giveing the error, for more information im running Arch Linux on  Kernel 5.10.5-arch1-1 with OpenDirectoryDownloader-linux-x64-self-contained

**Comment by KoalaBear84** [comment] 2021-01-11 22:23
Sorry for the late reaction. A little busy.

Do you use a version before [https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v1.9.2.8](https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v1.9.2.8) ? Because you use http instead of https it will not follow it, might cause it. Locally it doesn't give the same error.

Mega is currently unsupported, it IS on the long long list, but probably a complicated one with all the encryption etc.

**Comment by a8underscore** [comment] 2021-01-14 16:15
i used the latest ver & retested on the newer release, same error, but its just likely just an error because of mega being unsupported, should I close the issue?

**Comment by KoalaBear84** [comment] 2021-01-14 16:17
Hmm. Could you post a log of it like you did before?

**Comment by Chaphasilor** [comment] 2021-01-14 16:36
I don't remember encountering the issue before, but I probably wouldn't have noticed it anyway if there's another error, because then I'd worry about that other error \^\^

**Comment by MCOfficer** [comment] 2021-01-14 17:03
Can confirm this on linux, it works fine on windows. The "Press ESC" dialog comes after a while, but my server's version is a bit outdated (1.9.2.0), so it might be affected in later versions.

Regarding the SSL certificate: It can't be using the system truststore, because i can `curl https://mega.nz` just fine. [Coming from Java-land] I'd assume this is somehow caused by the truststore packaged with the application. Perhaps it is outdated and missing the certificate of whatever authority signed MEGA's certificate.

Either way, that "inner exception" would certainly be helpful.

**Comment by Chaphasilor** [comment] 2021-01-31 15:07
FYI I can't test on Ubuntu, but tested with two Debian installations (x64 and arm64), openSUSE (x64) and Windows, I don't get any errors or missing "Press ESC to exit" prompts anymore...

Tested with 1.9.3.6/8

**Comment by KoalaBear84** [comment] 2022-08-09 14:57
Looks like this one cannot be reproduced anymore.

```
Started with PID 60536
Which URL do you want to index?
http://mega.nz/folder/30MlkQib#RDOaGzmtFEHkxSYBaJSzVA
URL specified: http://mega.nz/folder/30MlkQib#RDOaGzmtFEHkxSYBaJSzVA
Started indexing!
┌─────────────────────────────────────────────────────────────────────────┐
│ KoalaBear84/OpenDirectoryDownloader v1.0.0.0                            │
├─────────────────────────────────────────────────────────────────────────┤
│ Press I for info (this)                                                 │
│ Press S for statistics                                                  │
│ Press T for thread info                                                 │
│ Press U for Save TXT                                                    │
│ Press J for Save JSON                                                   │
├─────────────────────────────────────────────────────────────────────────┤
│ Press ESC or X to EXIT                                                  │
└─────────────────────────────────────────────────────────────────────────┘

2022-08-09 16:56:24.0570  [7]  WARN OpenDirectoryIndexer.SetRootUrl Retrieved URL: https://mega.nz/#RDOaGzmtFEHkxSYBaJSzVA
Finshed indexing
|**Url:** [https://mega.nz/#RDOaGzmtFEHkxSYBaJSzV...](https://mega.nz/#RDOaGzmtFEHkxSYBaJSzVA/)|||
|:-|-:|-:|
|**Extension (Top 5)**|**Files**|**Size**|
|**Dirs:** 1 **Ext:** 0|**Total:** 0|**Total:** n/a|
|**Date (UTC):** 2022-08-09 14:56:23|**Time:** 00:00:02||

^(Created by [KoalaBear84's OpenDirectory Indexer v1.0.0.0](https://github.com/KoalaBear84/OpenDirectoryDownloader/))

No URLs to save
Http status codes
200: 1
Total files: 0, Total estimated size: n/a
Total directories: 1
Total HTTP requests: 1, Total HTTP traffic: 2.62 kiB
|**Url:** [https://mega.nz/#RDOaGzmtFEHkxSYBaJSzV...](https://mega.nz/#RDOaGzmtFEHkxSYBaJSzVA/)|||
|:-|-:|-:|
|**Extension (Top 5)**|**Files**|**Size**|
|**Dirs:** 1 **Ext:** 0|**Total:** 0|**Total:** n/a|
|**Date (UTC):** 2022-08-09 14:56:23|**Time:** 00:00:02||

^(Created by [KoalaBear84's OpenDirectory Indexer v1.0.0.0](https://github.com/KoalaBear84/OpenDirectoryDownloader/))

Finished indexing!
Press ESC to exit! Or C to copy to clipboard and quit!
```

**Comment by KoalaBear84** [comment] 2022-08-09 15:49
Closing because of the above. If we have another issue, I'll check it again.

**Closed by KoalaBear84** 2022-08-09 15:49 UTC
